export const RESEARCH_LIBRARY_COPY = {
  kk: {
    title: "Qazaqstan klimaty boiynsha zertteuler",
    lead: "Analitikalyq eseptter men interaktivti storytelling materialdaryn bir zherden tabyngyz.",
    searchPlaceholder: "Kilt soz, aumaq, taqyryp boiynsha izdeu",
    filters: "Suzgiler",
    allTypes: "Barlyq format",
    allTopics: "Barlyq taqyryp",
    allStatuses: "Barlyq martebe",
    results: "material",
    reset: "Tazalau",
    open: "Ashu",
    comingSoon: "Jaqynda",
    noResults: "Sai kesetin material tabylmady",
    noResultsHint: "Izdeu sozderin qysqartyp nemese suzgilerdi ozgertip koringiz.",
    backHome: "Basty bet",
    map: "Geoportal",
    typeLabels: {
      report: "Analitikalyq esep",
      storytelling: "Storytelling",
    },
    statusLabels: {
      available: "Qoljetimdi",
      planned: "Josparda",
      draft: "Daiyndaluda",
    },
    topicLabels: {
      fire: "Ortter",
      drought: "Qurg'aqshylyq",
      water: "Su jane tasqyn",
      cryosphere: "Muzdyqtar",
      land: "Zher jabyndysy",
    },
  },
  en: {
    title: "Kazakhstan Climate Research",
    lead: "Find analytical reports and interactive storytelling materials in one searchable library.",
    searchPlaceholder: "Search by keyword, region, or topic",
    filters: "Filters",
    allTypes: "All formats",
    allTopics: "All topics",
    allStatuses: "All statuses",
    results: "materials",
    reset: "Reset",
    open: "Open",
    comingSoon: "Coming soon",
    noResults: "No matching materials",
    noResultsHint: "Try a broader keyword or change the filters.",
    backHome: "Home",
    map: "Geoportal",
    typeLabels: {
      report: "Analytical report",
      storytelling: "Storytelling",
    },
    statusLabels: {
      available: "Available",
      planned: "Planned",
      draft: "In draft",
    },
    topicLabels: {
      fire: "Fire",
      drought: "Drought",
      water: "Water and floods",
      cryosphere: "Cryosphere",
      land: "Land cover",
    },
  },
  ru: {
    title: "Исследования климата Казахстана",
    lead: "Каталог аналитических отчетов и интерактивных storytelling-материалов с поиском и фильтрами.",
    searchPlaceholder: "Поиск по ключевым словам, региону или теме",
    filters: "Фильтры",
    allTypes: "Все форматы",
    allTopics: "Все темы",
    allStatuses: "Все статусы",
    results: "материалов",
    reset: "Сбросить",
    open: "Открыть",
    comingSoon: "Скоро",
    noResults: "Материалы не найдены",
    noResultsHint: "Попробуйте расширить запрос или изменить фильтры.",
    backHome: "Главная",
    map: "Геопортал",
    typeLabels: {
      report: "Аналитический отчет",
      storytelling: "Storytelling",
    },
    statusLabels: {
      available: "Доступен",
      planned: "В плане",
      draft: "Готовится",
    },
    topicLabels: {
      fire: "Пожары",
      drought: "Засуха",
      water: "Вода и паводки",
      cryosphere: "Криосфера",
      land: "Земной покров",
    },
  },
};

export const RESEARCH_MATERIALS = [
  {
    id: "wildfire-dynamics-2001-2024",
    type: "report",
    topic: "fire",
    status: "available",
    period: "2001-2024",
    href: "/report",
    title: {
      kk: "Qazaqstandaghy ortter dinamikasy",
      en: "Wildfire Dynamics in Kazakhstan",
      ru: "Динамика пожаров в Казахстане",
    },
    description: {
      kk: "MODIS/VIIRS derekteri negizinde ortterding uaqyt, aumaq jane landshaft boiynsha ozgerisin taldau.",
      en: "A MODIS/VIIRS-based analysis of fire changes by time, region and landscape.",
      ru: "Анализ изменений пожаров по времени, регионам и ландшафтам на основе MODIS/VIIRS.",
    },
    keywords: {
      kk: ["ort", "MODIS", "VIIRS", "tarikh", "oblys"],
      en: ["fire", "MODIS", "VIIRS", "history", "regions"],
      ru: ["пожары", "MODIS", "VIIRS", "история", "области"],
    },
  },
  {
    id: "kazakhstan-fire-story",
    type: "storytelling",
    topic: "fire",
    status: "planned",
    period: "2001-2024",
    title: {
      kk: "Qazaqstan ortterining kartaly tarikhy",
      en: "A Mapped History of Kazakhstan Fires",
      ru: "Картографическая история пожаров Казахстана",
    },
    description: {
      kk: "24 jyldyq ort oqigalaryn kartalar, satistikalar jane aumaqtyq hikayalar arqyly tusindiretin interaktivti material.",
      en: "An interactive story explaining 24 years of fire events through maps, statistics and regional narratives.",
      ru: "Интерактивный материал о 24 годах пожаров через карты, статистику и региональные истории.",
    },
    keywords: {
      kk: ["story", "karta", "ort", "region", "timeline"],
      en: ["story", "map", "fire", "region", "timeline"],
      ru: ["история", "карта", "пожары", "регион", "таймлайн"],
    },
  },
  {
    id: "steppe-drought-pulse",
    type: "storytelling",
    topic: "drought",
    status: "planned",
    period: "2017-2026",
    title: {
      kk: "Dalanyng qurg'aqshylyq pulsi",
      en: "Drought Pulse of the Steppe",
      ru: "Пульс засухи в степи",
    },
    description: {
      kk: "NDVI, VHI jane klimat indikatorlary arqyly vegetatsiya stressining mawsymdyq korinisleri.",
      en: "Seasonal views of vegetation stress through NDVI, VHI and climate indicators.",
      ru: "Сезонные проявления стресса растительности через NDVI, VHI и климатические индикаторы.",
    },
    keywords: {
      kk: ["qurg'aqshylyq", "NDVI", "VHI", "dala", "vegetatsiya"],
      en: ["drought", "NDVI", "VHI", "steppe", "vegetation"],
      ru: ["засуха", "NDVI", "VHI", "степь", "растительность"],
    },
  },
  {
    id: "glacier-retreat",
    type: "report",
    topic: "cryosphere",
    status: "draft",
    period: "2016-2026",
    title: {
      kk: "Muzdyqtardyng sheginui: Tien Shan jane Altai",
      en: "Glacier Retreat: Tien Shan and Altai",
      ru: "Отступление ледников: Тянь-Шань и Алтай",
    },
    description: {
      kk: "Sentinel-2 suretteri boiynsha muzdyq shegaralary, qar jabyndysy jane biyiktik beldeuleri.",
      en: "Sentinel-2 based glacier outlines, snow cover and elevation-zone indicators.",
      ru: "Контуры ледников, снежный покров и высотные зоны по данным Sentinel-2.",
    },
    keywords: {
      kk: ["muzdyq", "Tien Shan", "Altai", "qar", "Sentinel"],
      en: ["glacier", "Tien Shan", "Altai", "snow", "Sentinel"],
      ru: ["ледники", "Тянь-Шань", "Алтай", "снег", "Sentinel"],
    },
  },
  {
    id: "water-stress-flood-signals",
    type: "report",
    topic: "water",
    status: "planned",
    period: "2018-2026",
    title: {
      kk: "Su stressi jane tasqyn signaldary",
      en: "Water Stress and Flood Signals",
      ru: "Водный стресс и сигналы паводков",
    },
    description: {
      kk: "Su ainalymyn, su qoimalaryn jane tasqyn izderin gharysh indikatorlary arqyly saraptau.",
      en: "Satellite indicators for water cycles, reservoirs and flood traces.",
      ru: "Спутниковые индикаторы водного цикла, водохранилищ и следов паводков.",
    },
    keywords: {
      kk: ["su", "tasqyn", "NDWI", "kol", "qoima"],
      en: ["water", "flood", "NDWI", "lake", "reservoir"],
      ru: ["вода", "паводок", "NDWI", "озеро", "водохранилище"],
    },
  },
  {
    id: "land-cover-climate-pressure",
    type: "storytelling",
    topic: "land",
    status: "planned",
    period: "2017-2023",
    title: {
      kk: "Zher jabyndysy jane klimat qysymy",
      en: "Land Cover and Climate Pressure",
      ru: "Земной покров и климатическое давление",
    },
    description: {
      kk: "ESRI land-cover derekteri arqyly dala, egistik, su jane qala keinstikterining ozgerisin korsetetin hikaya.",
      en: "A visual story of steppe, cropland, water and urban change using ESRI land-cover data.",
      ru: "Визуальная история изменений степей, пашни, воды и городских территорий по ESRI land-cover.",
    },
    keywords: {
      kk: ["zher jabyndysy", "ESRI", "egistik", "dala", "qala"],
      en: ["land cover", "ESRI", "cropland", "steppe", "urban"],
      ru: ["земной покров", "ESRI", "пашня", "степь", "город"],
    },
  },
];

export const getResearchText = (value, language) => value?.[language] ?? value?.kk ?? value?.en ?? "";
