export const HISTORICAL_WILDFIRE_CASES = [
  {
    id: 'abai-2023',
    type: 'wildfire',
    title: 'Пожары в Абайской области 2023',
    location: 'Резерват «Семей Орманы», Абайская область',
    period: '8–16 июн. 2023',
    startDate: '2023-06-08',
    endDate: '2023-06-16',
    burnedAreaHa: 60000,
    territory: 'Ленточный сосновый бор',
    severity: 'Чрезвычайный',
    impact: 'Погибло 14 человек; объявлено общенациональное ЧС',
    sourceLabel: 'Astana Times, TuraNews, Kazakhstan Today',
    sourceNote: 'Контур пожарища — схематичная АОИ до загрузки официальных геоданных.',
    color: '#f97316',
    bbox: [79.42, 49.72, 80.78, 50.58],
    center: [80.1, 50.15],
    geometry: {
      type: 'Polygon',
      coordinates: [[
        [79.52, 49.85],
        [79.82, 49.72],
        [80.36, 49.8],
        [80.78, 50.08],
        [80.6, 50.46],
        [80.08, 50.58],
        [79.56, 50.34],
        [79.42, 50.02],
        [79.52, 49.85],
      ]],
    },
    timeline: [
      { label: 'Июн 8', areaHa: 2000 },
      { label: 'Июн 10', areaHa: 30000 },
      { label: 'Июн 13', areaHa: 60000 },
      { label: 'Июн 16', areaHa: 60000 },
    ],
    landCover: [
      { label: 'Лес', value: 82, color: '#22c55e' },
      { label: 'Трава/кустарник', value: 12, color: '#a3e635' },
      { label: 'Прочее', value: 6, color: '#94a3b8' },
    ],
    stats: [
      { label: 'Площадь пожара', value: '60 000 га' },
      { label: 'Продолжительность', value: '9 дней' },
      { label: 'Регион', value: 'Абайская' },
      { label: 'Статус', value: 'Локализовано' },
    ],
  },
  {
    id: 'kostanay-2022',
    type: 'wildfire',
    title: 'Пожар в лесостепи Костанайской области 2022',
    location: 'Аулиекольский район, Костанайская область',
    period: '2–7 сент. 2022',
    startDate: '2022-09-02',
    endDate: '2022-09-07',
    burnedAreaHa: 43000,
    territory: 'Лесостепь и населённые пункты',
    severity: 'Крупный',
    impact: 'Тысячи человек эвакуированы; повреждены дома и лесные угодья',
    sourceLabel: 'Kazinform, TuraNews, QazMonitor',
    sourceNote: 'Контур пожарища — схематичная АОИ до загрузки официальных геоданных.',
    color: '#ef4444',
    bbox: [63.82, 51.55, 64.86, 52.34],
    center: [64.32, 51.98],
    geometry: {
      type: 'Polygon',
      coordinates: [[
        [63.9, 51.72],
        [64.24, 51.55],
        [64.72, 51.62],
        [64.86, 51.96],
        [64.62, 52.26],
        [64.08, 52.34],
        [63.82, 52.06],
        [63.9, 51.72],
      ]],
    },
    timeline: [
      { label: 'Сент 2', areaHa: 9400 },
      { label: 'Сент 4', areaHa: 43000 },
      { label: 'Сент 7', areaHa: 43000 },
    ],
    landCover: [
      { label: 'Лес', value: 58, color: '#22c55e' },
      { label: 'Степь', value: 31, color: '#eab308' },
      { label: 'Окрестности посёлков', value: 11, color: '#f97316' },
    ],
    stats: [
      { label: 'Площадь пожара', value: '43 000 га' },
      { label: 'Продолжительность', value: '6 дней' },
      { label: 'Регион', value: 'Костанайская' },
      { label: 'Статус', value: 'Локализовано' },
    ],
  },
  {
    id: 'pavlodar-2010',
    type: 'wildfire',
    title: 'Пожар в бору 2010, Павлодарская область',
    location: 'Ертіс Орманы, Павлодарская область',
    period: '8–10 сент. 2010',
    startDate: '2010-09-08',
    endDate: '2010-09-10',
    burnedAreaHa: 3300,
    territory: 'Приграничный сосновый бор',
    severity: 'Серьёзный',
    impact: 'По архивным данным погибло 6–7 человек',
    sourceLabel: 'Inform.kz, TerraDaily, UN-SPIDER',
    sourceNote: 'Контур пожарища — схематичная АОИ до загрузки официальных геоданных.',
    color: '#fb923c',
    bbox: [77.58, 51.03, 78.12, 51.45],
    center: [77.86, 51.24],
    geometry: {
      type: 'Polygon',
      coordinates: [[
        [77.64, 51.08],
        [77.9, 51.03],
        [78.12, 51.18],
        [78.02, 51.4],
        [77.72, 51.45],
        [77.58, 51.28],
        [77.64, 51.08],
      ]],
    },
    timeline: [
      { label: 'Сент 8', areaHa: 1200 },
      { label: 'Сент 9', areaHa: 3300 },
      { label: 'Сент 10', areaHa: 3300 },
    ],
    landCover: [
      { label: 'Лес', value: 88, color: '#22c55e' },
      { label: 'Трава/кустарник', value: 8, color: '#a3e635' },
      { label: 'Прочее', value: 4, color: '#94a3b8' },
    ],
    stats: [
      { label: 'Площадь пожара', value: '3 300 га' },
      { label: 'Продолжительность', value: '3 дня' },
      { label: 'Регион', value: 'Павлодарская' },
      { label: 'Статус', value: 'Ликвидировано' },
    ],
  },
  {
    id: 'ridder-2021',
    type: 'wildfire',
    title: 'Пожар в Риддере 2021',
    location: 'Риддер, Восточно-Казахстанская область',
    period: '10 мая 2021',
    startDate: '2021-05-10',
    endDate: '2021-05-10',
    burnedAreaHa: 310,
    territory: 'Переходная зона лес–городская застройка',
    severity: 'Локальная ЧС',
    impact: 'Погиб 1 человек; повреждены жилые дома',
    sourceLabel: 'Orda.kz, Reuters',
    sourceNote: 'Контур пожарища — схематичная АОИ до загрузки официальных геоданных.',
    color: '#f59e0b',
    bbox: [83.28, 50.28, 83.64, 50.48],
    center: [83.5, 50.36],
    geometry: {
      type: 'Polygon',
      coordinates: [[
        [83.32, 50.31],
        [83.5, 50.28],
        [83.64, 50.36],
        [83.56, 50.46],
        [83.36, 50.48],
        [83.28, 50.38],
        [83.32, 50.31],
      ]],
    },
    timeline: [
      { label: 'Май 10', areaHa: 310 },
    ],
    landCover: [
      { label: 'Лесной массив', value: 55, color: '#22c55e' },
      { label: 'Окрестности посёлков', value: 32, color: '#f97316' },
      { label: 'Прочее', value: 13, color: '#94a3b8' },
    ],
    stats: [
      { label: 'Площадь пожара', value: '310 га' },
      { label: 'Продолжительность', value: '1 день' },
      { label: 'Регион', value: 'ВКО' },
      { label: 'Статус', value: 'Ликвидировано' },
    ],
  },
];

export const getHistoricalWildfireCase = (id) =>
  HISTORICAL_WILDFIRE_CASES.find((item) => item.id === id) || null;

export const buildHistoricalWildfireFeatureCollection = (wildfireCase) => {
  if (!wildfireCase) {
    return { type: 'FeatureCollection', features: [] };
  }
  return {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          id: wildfireCase.id,
          title: wildfireCase.title,
          location: wildfireCase.location,
          burnedAreaHa: wildfireCase.burnedAreaHa,
          color: wildfireCase.color,
          eventType: 'wildfire',
        },
        geometry: wildfireCase.geometry,
      },
      {
        type: 'Feature',
        properties: {
          id: `${wildfireCase.id}-center`,
          title: wildfireCase.title,
          color: wildfireCase.color,
          eventType: 'wildfire',
        },
        geometry: {
          type: 'Point',
          coordinates: wildfireCase.center,
        },
      },
    ],
  };
};
